create extension if not exists "pgcrypto";
create table if not exists organizations ( id uuid primary key default gen_random_uuid(), name text not null );
create table if not exists profiles ( id uuid primary key references auth.users on delete cascade, org_id uuid not null references organizations(id) on delete cascade, role text not null check (role in ('owner','manager','staff','viewer')) );
create table if not exists branches ( id text primary key, org_id uuid not null references organizations(id) on delete cascade, name text not null, address text not null );
create table if not exists orders ( id uuid primary key default gen_random_uuid(), org_id uuid not null references organizations(id) on delete cascade, supplier_name text not null, branch_id text references branches(id), created_at timestamptz not null default now(), created_by uuid references auth.users, notes text );
create table if not exists order_items ( order_id uuid references orders(id) on delete cascade, item_name text not null, qty numeric not null, unit text, primary key (order_id, item_name) );
alter table organizations enable row level security;
alter table profiles enable row level security;
alter table branches enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
create or replace function current_profile() returns profiles language sql security definer set search_path = public as $$ select p.* from profiles p where p.id = auth.uid() $$;
create policy org_read_branches on branches for select using (org_id = current_profile().org_id);
create policy org_read_orders on orders for select using (org_id = current_profile().org_id);
create policy org_read_order_items on order_items for select using (exists (select 1 from orders o where o.id = order_items.order_id and o.org_id = current_profile().org_id));
create policy orders_insert on orders for insert with check (org_id = current_profile().org_id and current_profile().role in ('owner','manager','staff'));
create policy orders_update on orders for update using (org_id = current_profile().org_id and current_profile().role in ('owner','manager')) with check (org_id = current_profile().org_id);
create policy order_items_write on order_items for all using (exists (select 1 from orders o where o.id = order_items.order_id and o.org_id = current_profile().org_id)) with check (exists (select 1 from orders o where o.id = order_items.order_id and o.org_id = current_profile().org_id));
create policy profiles_self_select on profiles for select using (id = auth.uid());
create policy profiles_self_insert on profiles for insert with check (id = auth.uid());
create policy profiles_self_update on profiles for update using (id = auth.uid()) with check (id = auth.uid());
